import { IPlace } from "../../types/index";

export const WholeWeather: IPlace[] = [
  {
    weather: [
      {
        temprature: 10,
        humidity: 30,
        pressure: 140,
        windspeed: 2,
        id: 0,
      },
      {
        temprature: 9,
        humidity: 31,
        pressure: 138,
        windspeed: 4,
        id: 1,
      },
      {
        temprature: 8,
        humidity: 40,
        pressure: 136,
        windspeed: 3,
        id: 2,
      },
      {
        temprature: 10,
        humidity: 30,
        pressure: 140,
        windspeed: 3,
        id: 3,
      },
      {
        temprature: 11,
        humidity: 30,
        pressure: 143,
        windspeed: 0,
        id: 4,
      },
      {
        temprature: 12,
        humidity: 30,
        pressure: 143,
        windspeed: 1,
        id: 5,
      },
      {
        temprature: 12,
        humidity: 30,
        pressure: 143,
        windspeed: 1,
        id: 6,
      },
      {
        temprature: 11,
        humidity: 30,
        pressure: 144,
        windspeed: 4,
        id: 7,
      },
      {
        temprature: 12,
        humidity: 30,
        pressure: 144,
        windspeed: 5,
        id: 8,
      },
      {
        temprature: 13,
        humidity: 30,
        pressure: 145,
        windspeed: 3,
        id: 9,
      },
      {
        temprature: 15,
        humidity: 30,
        pressure: 145,
        windspeed: 4,
        id: 10,
      },
      {
        temprature: 16,
        humidity: 30,
        pressure: 145,
        windspeed: 5,
        id: 11,
      },
      {
        temprature: 16,
        humidity: 30,
        pressure: 145,
        windspeed: 6,
        id: 12,
      },
      {
        temprature: 16,
        humidity: 30,
        pressure: 146,
        windspeed: 2,
        id: 13,
      },
      {
        temprature: 16,
        humidity: 30,
        pressure: 145,
        windspeed: 2,
        id: 14,
      },
      {
        temprature: 17,
        humidity: 30,
        pressure: 145,
        windspeed: 3,
        id: 15,
      },
      {
        temprature: 15,
        humidity: 30,
        pressure: 143,
        windspeed: 5,
        id: 16,
      },
      {
        temprature: 13,
        humidity: 30,
        pressure: 143,
        windspeed: 1,
        id: 17,
      },
      {
        temprature: 12,
        humidity: 30,
        pressure: 142,
        windspeed: 2,
        id: 18,
      },
      {
        temprature: 11,
        humidity: 30,
        pressure: 142,
        windspeed: 3,
        id: 19,
      },
      {
        temprature: 11,
        humidity: 30,
        pressure: 140,
        windspeed: 3,
        id: 20,
      },
      {
        temprature: 9,
        humidity: 30,
        pressure: 139,
        windspeed: 2,
        id: 21,
      },
      {
        temprature: 8,
        humidity: 30,
        pressure: 138,
        windspeed: 5,
        id: 22,
      },
      {
        temprature: 9,
        humidity: 30,
        pressure: 137,
        windspeed: 2,
        id: 23,
      },
    ],
    place: "Minsk",
    time: new Date(2024, 1, 16),
    id: 0,
  },
  {
    weather: [
      {
        temprature: 10,
        humidity: 30,
        pressure: 140,
        windspeed: 2,
        id: 0,
      },
      {
        temprature: 9,
        humidity: 31,
        pressure: 138,
        windspeed: 4,
        id: 1,
      },
      {
        temprature: 8,
        humidity: 40,
        pressure: 136,
        windspeed: 3,
        id: 2,
      },
      {
        temprature: 10,
        humidity: 30,
        pressure: 140,
        windspeed: 3,
        id: 3,
      },
      {
        temprature: 11,
        humidity: 30,
        pressure: 143,
        windspeed: 0,
        id: 4,
      },
      {
        temprature: 12,
        humidity: 30,
        pressure: 143,
        windspeed: 1,
        id: 5,
      },
      {
        temprature: 12,
        humidity: 30,
        pressure: 143,
        windspeed: 1,
        id: 6,
      },
      {
        temprature: 11,
        humidity: 30,
        pressure: 144,
        windspeed: 4,
        id: 7,
      },
      {
        temprature: 12,
        humidity: 30,
        pressure: 144,
        windspeed: 5,
        id: 8,
      },
      {
        temprature: 13,
        humidity: 30,
        pressure: 145,
        windspeed: 3,
        id: 9,
      },
      {
        temprature: 15,
        humidity: 30,
        pressure: 145,
        windspeed: 4,
        id: 10,
      },
      {
        temprature: 16,
        humidity: 30,
        pressure: 145,
        windspeed: 5,
        id: 11,
      },
      {
        temprature: 16,
        humidity: 30,
        pressure: 145,
        windspeed: 6,
        id: 12,
      },
      {
        temprature: 16,
        humidity: 30,
        pressure: 146,
        windspeed: 2,
        id: 13,
      },
      {
        temprature: 16,
        humidity: 30,
        pressure: 145,
        windspeed: 2,
        id: 14,
      },
      {
        temprature: 17,
        humidity: 30,
        pressure: 145,
        windspeed: 3,
        id: 15,
      },
      {
        temprature: 15,
        humidity: 30,
        pressure: 143,
        windspeed: 5,
        id: 16,
      },
      {
        temprature: 13,
        humidity: 30,
        pressure: 143,
        windspeed: 1,
        id: 17,
      },
      {
        temprature: 12,
        humidity: 30,
        pressure: 142,
        windspeed: 2,
        id: 18,
      },
      {
        temprature: 11,
        humidity: 30,
        pressure: 142,
        windspeed: 3,
        id: 19,
      },
      {
        temprature: 11,
        humidity: 30,
        pressure: 140,
        windspeed: 3,
        id: 20,
      },
      {
        temprature: 9,
        humidity: 30,
        pressure: 139,
        windspeed: 2,
        id: 21,
      },
      {
        temprature: 8,
        humidity: 30,
        pressure: 138,
        windspeed: 5,
        id: 22,
      },
      {
        temprature: 9,
        humidity: 30,
        pressure: 137,
        windspeed: 2,
        id: 23,
      },
    ],
    place: "Gomel",
    time: new Date(2024, 1, 16),
    id: 1,
  },
  {
    weather: [
      {
        temprature: 10,
        humidity: 30,
        pressure: 140,
        windspeed: 2,
        id: 0,
      },
      {
        temprature: 9,
        humidity: 31,
        pressure: 138,
        windspeed: 4,
        id: 1,
      },
      {
        temprature: 8,
        humidity: 40,
        pressure: 136,
        windspeed: 3,
        id: 2,
      },
      {
        temprature: 10,
        humidity: 30,
        pressure: 140,
        windspeed: 3,
        id: 3,
      },
      {
        temprature: 11,
        humidity: 30,
        pressure: 143,
        windspeed: 0,
        id: 4,
      },
      {
        temprature: 12,
        humidity: 30,
        pressure: 143,
        windspeed: 1,
        id: 5,
      },
      {
        temprature: 12,
        humidity: 30,
        pressure: 143,
        windspeed: 1,
        id: 6,
      },
      {
        temprature: 11,
        humidity: 30,
        pressure: 144,
        windspeed: 4,
        id: 7,
      },
      {
        temprature: 12,
        humidity: 30,
        pressure: 144,
        windspeed: 5,
        id: 8,
      },
      {
        temprature: 13,
        humidity: 30,
        pressure: 145,
        windspeed: 3,
        id: 9,
      },
      {
        temprature: 15,
        humidity: 30,
        pressure: 145,
        windspeed: 4,
        id: 10,
      },
      {
        temprature: 16,
        humidity: 30,
        pressure: 145,
        windspeed: 5,
        id: 11,
      },
      {
        temprature: 16,
        humidity: 30,
        pressure: 145,
        windspeed: 6,
        id: 12,
      },
      {
        temprature: 16,
        humidity: 30,
        pressure: 146,
        windspeed: 2,
        id: 13,
      },
      {
        temprature: 16,
        humidity: 30,
        pressure: 145,
        windspeed: 2,
        id: 14,
      },
      {
        temprature: 17,
        humidity: 30,
        pressure: 145,
        windspeed: 3,
        id: 15,
      },
      {
        temprature: 15,
        humidity: 30,
        pressure: 143,
        windspeed: 5,
        id: 16,
      },
      {
        temprature: 13,
        humidity: 30,
        pressure: 143,
        windspeed: 1,
        id: 17,
      },
      {
        temprature: 12,
        humidity: 30,
        pressure: 142,
        windspeed: 2,
        id: 18,
      },
      {
        temprature: 11,
        humidity: 30,
        pressure: 142,
        windspeed: 3,
        id: 19,
      },
      {
        temprature: 11,
        humidity: 30,
        pressure: 140,
        windspeed: 3,
        id: 20,
      },
      {
        temprature: 9,
        humidity: 30,
        pressure: 139,
        windspeed: 2,
        id: 21,
      },
      {
        temprature: 8,
        humidity: 30,
        pressure: 138,
        windspeed: 5,
        id: 22,
      },
      {
        temprature: 9,
        humidity: 30,
        pressure: 137,
        windspeed: 2,
        id: 23,
      },
    ],
    place: "Brest",
    time: new Date(2024, 1, 16),
    id: 2,
  },
  {
    weather: [
      {
        temprature: 10,
        humidity: 30,
        pressure: 140,
        windspeed: 2,
        id: 0,
      },
      {
        temprature: 9,
        humidity: 31,
        pressure: 138,
        windspeed: 4,
        id: 1,
      },
      {
        temprature: 8,
        humidity: 40,
        pressure: 136,
        windspeed: 3,
        id: 2,
      },
      {
        temprature: 10,
        humidity: 30,
        pressure: 140,
        windspeed: 3,
        id: 3,
      },
      {
        temprature: 11,
        humidity: 30,
        pressure: 143,
        windspeed: 0,
        id: 4,
      },
      {
        temprature: 12,
        humidity: 30,
        pressure: 143,
        windspeed: 1,
        id: 5,
      },
      {
        temprature: 12,
        humidity: 30,
        pressure: 143,
        windspeed: 1,
        id: 6,
      },
      {
        temprature: 11,
        humidity: 30,
        pressure: 144,
        windspeed: 4,
        id: 7,
      },
      {
        temprature: 12,
        humidity: 30,
        pressure: 144,
        windspeed: 5,
        id: 8,
      },
      {
        temprature: 13,
        humidity: 30,
        pressure: 145,
        windspeed: 3,
        id: 9,
      },
      {
        temprature: 15,
        humidity: 30,
        pressure: 145,
        windspeed: 4,
        id: 10,
      },
      {
        temprature: 16,
        humidity: 30,
        pressure: 145,
        windspeed: 5,
        id: 11,
      },
      {
        temprature: 16,
        humidity: 30,
        pressure: 145,
        windspeed: 6,
        id: 12,
      },
      {
        temprature: 16,
        humidity: 30,
        pressure: 146,
        windspeed: 2,
        id: 13,
      },
      {
        temprature: 16,
        humidity: 30,
        pressure: 145,
        windspeed: 2,
        id: 14,
      },
      {
        temprature: 17,
        humidity: 30,
        pressure: 145,
        windspeed: 3,
        id: 15,
      },
      {
        temprature: 15,
        humidity: 30,
        pressure: 143,
        windspeed: 5,
        id: 16,
      },
      {
        temprature: 13,
        humidity: 30,
        pressure: 143,
        windspeed: 1,
        id: 17,
      },
      {
        temprature: 12,
        humidity: 30,
        pressure: 142,
        windspeed: 2,
        id: 18,
      },
      {
        temprature: 11,
        humidity: 30,
        pressure: 142,
        windspeed: 3,
        id: 19,
      },
      {
        temprature: 11,
        humidity: 30,
        pressure: 140,
        windspeed: 3,
        id: 20,
      },
      {
        temprature: 9,
        humidity: 30,
        pressure: 139,
        windspeed: 2,
        id: 21,
      },
      {
        temprature: 8,
        humidity: 30,
        pressure: 138,
        windspeed: 5,
        id: 22,
      },
      {
        temprature: 9,
        humidity: 30,
        pressure: 137,
        windspeed: 2,
        id: 23,
      },
    ],
    place: "Mogilev",
    time: new Date(2024, 1, 16),
    id: 3,
  },
  {
    weather: [
      {
        temprature: 10,
        humidity: 30,
        pressure: 140,
        windspeed: 2,
        id: 0,
      },
      {
        temprature: 9,
        humidity: 31,
        pressure: 138,
        windspeed: 4,
        id: 1,
      },
      {
        temprature: 8,
        humidity: 40,
        pressure: 136,
        windspeed: 3,
        id: 2,
      },
      {
        temprature: 10,
        humidity: 30,
        pressure: 140,
        windspeed: 3,
        id: 3,
      },
      {
        temprature: 11,
        humidity: 30,
        pressure: 143,
        windspeed: 0,
        id: 4,
      },
      {
        temprature: 12,
        humidity: 30,
        pressure: 143,
        windspeed: 1,
        id: 5,
      },
      {
        temprature: 12,
        humidity: 30,
        pressure: 143,
        windspeed: 1,
        id: 6,
      },
      {
        temprature: 11,
        humidity: 30,
        pressure: 144,
        windspeed: 4,
        id: 7,
      },
      {
        temprature: 12,
        humidity: 30,
        pressure: 144,
        windspeed: 5,
        id: 8,
      },
      {
        temprature: 13,
        humidity: 30,
        pressure: 145,
        windspeed: 3,
        id: 9,
      },
      {
        temprature: 15,
        humidity: 30,
        pressure: 145,
        windspeed: 4,
        id: 10,
      },
      {
        temprature: 16,
        humidity: 30,
        pressure: 145,
        windspeed: 5,
        id: 11,
      },
      {
        temprature: 16,
        humidity: 30,
        pressure: 145,
        windspeed: 6,
        id: 12,
      },
      {
        temprature: 16,
        humidity: 30,
        pressure: 146,
        windspeed: 2,
        id: 13,
      },
      {
        temprature: 16,
        humidity: 30,
        pressure: 145,
        windspeed: 2,
        id: 14,
      },
      {
        temprature: 17,
        humidity: 30,
        pressure: 145,
        windspeed: 3,
        id: 15,
      },
      {
        temprature: 15,
        humidity: 30,
        pressure: 143,
        windspeed: 5,
        id: 16,
      },
      {
        temprature: 13,
        humidity: 30,
        pressure: 143,
        windspeed: 1,
        id: 17,
      },
      {
        temprature: 12,
        humidity: 30,
        pressure: 142,
        windspeed: 2,
        id: 18,
      },
      {
        temprature: 11,
        humidity: 30,
        pressure: 142,
        windspeed: 3,
        id: 19,
      },
      {
        temprature: 11,
        humidity: 30,
        pressure: 140,
        windspeed: 3,
        id: 20,
      },
      {
        temprature: 9,
        humidity: 30,
        pressure: 139,
        windspeed: 2,
        id: 21,
      },
      {
        temprature: 8,
        humidity: 30,
        pressure: 138,
        windspeed: 5,
        id: 22,
      },
      {
        temprature: 9,
        humidity: 30,
        pressure: 137,
        windspeed: 2,
        id: 23,
      },
    ],
    place: "Grodno",
    time: new Date(2024, 1, 16),
    id: 3,
  },
  {
    weather: [
      {
        temprature: 10,
        humidity: 30,
        pressure: 140,
        windspeed: 2,
        id: 0,
      },
      {
        temprature: 9,
        humidity: 31,
        pressure: 138,
        windspeed: 4,
        id: 1,
      },
      {
        temprature: 8,
        humidity: 40,
        pressure: 136,
        windspeed: 3,
        id: 2,
      },
      {
        temprature: 10,
        humidity: 30,
        pressure: 140,
        windspeed: 3,
        id: 3,
      },
      {
        temprature: 11,
        humidity: 30,
        pressure: 143,
        windspeed: 0,
        id: 4,
      },
      {
        temprature: 12,
        humidity: 30,
        pressure: 143,
        windspeed: 1,
        id: 5,
      },
      {
        temprature: 12,
        humidity: 30,
        pressure: 143,
        windspeed: 1,
        id: 6,
      },
      {
        temprature: 11,
        humidity: 30,
        pressure: 144,
        windspeed: 4,
        id: 7,
      },
      {
        temprature: 12,
        humidity: 30,
        pressure: 144,
        windspeed: 5,
        id: 8,
      },
      {
        temprature: 13,
        humidity: 30,
        pressure: 145,
        windspeed: 3,
        id: 9,
      },
      {
        temprature: 15,
        humidity: 30,
        pressure: 145,
        windspeed: 4,
        id: 10,
      },
      {
        temprature: 16,
        humidity: 30,
        pressure: 145,
        windspeed: 5,
        id: 11,
      },
      {
        temprature: 16,
        humidity: 30,
        pressure: 145,
        windspeed: 6,
        id: 12,
      },
      {
        temprature: 16,
        humidity: 30,
        pressure: 146,
        windspeed: 2,
        id: 13,
      },
      {
        temprature: 16,
        humidity: 30,
        pressure: 145,
        windspeed: 2,
        id: 14,
      },
      {
        temprature: 17,
        humidity: 30,
        pressure: 145,
        windspeed: 3,
        id: 15,
      },
      {
        temprature: 15,
        humidity: 30,
        pressure: 143,
        windspeed: 5,
        id: 16,
      },
      {
        temprature: 13,
        humidity: 30,
        pressure: 143,
        windspeed: 1,
        id: 17,
      },
      {
        temprature: 12,
        humidity: 30,
        pressure: 142,
        windspeed: 2,
        id: 18,
      },
      {
        temprature: 11,
        humidity: 30,
        pressure: 142,
        windspeed: 3,
        id: 19,
      },
      {
        temprature: 11,
        humidity: 30,
        pressure: 140,
        windspeed: 3,
        id: 20,
      },
      {
        temprature: 9,
        humidity: 30,
        pressure: 139,
        windspeed: 2,
        id: 21,
      },
      {
        temprature: 8,
        humidity: 30,
        pressure: 138,
        windspeed: 5,
        id: 22,
      },
      {
        temprature: 9,
        humidity: 30,
        pressure: 137,
        windspeed: 2,
        id: 23,
      },
    ],
    place: "Vitebsk",
    time: new Date(2024, 1, 16),
    id: 3,
  },
];
